<?php

/**
 * @file
 * Integrates Drupal Entities with Doctrine ORM.
 */

function doctrine_entity_init() {
//   module_load_install('doctrine_entity');
//   doctrine_entity_install();
  $user = doctrine()->find('Drupal\doctrine\Entity\User', 1);
}

/**
 * Implements hook_entity_info_alter().
 */
function doctrine_entity_entity_info_alter(&$entity_info) {
  // Sets the entity class for users to a class test value.
  $entity_info['user']['entity class'] = 'Drupal\doctrine\Entity\User';

  $entity_info['filter_format']['label'] = 'Filter Format';
  $entity_info['filter_format']['fieldable'] = FALSE;
  $entity_info['filter_format']['base table'] = 'filter_format';
  $entity_info['filter_format']['entity class'] = 'Drupal\doctrine\Entity\FilterFormat';
  $entity_info['filter_format']['controller class'] = '';
  $entity_info['filter_format']['bundles'] = '';
}
