<?php

/**
 * @file
 * Integrates Drupal Entities with Doctrine ORM.
 */

function entity_init() {
  $user = doctrine()->find('Drupal\entity\User', 1);
  $format = $user->getFilterFormat();
  $debug = true;
}

/**
 * Implements hook_entity_info_alter().
 */
function entity_entity_info_alter(&$entity_info) {
  $entity_info['user']['entity class'] = 'Drupal\entity\User';
  $entity_info['node']['entity class'] = 'Drupal\entity\Node';

  $entity_info['filter_format']['label'] = 'Filter Format';
  $entity_info['filter_format']['fieldable'] = FALSE;
  $entity_info['filter_format']['base table'] = 'filter_format';
  $entity_info['filter_format']['entity class'] = 'Drupal\entity\FilterFormat';
  $entity_info['filter_format']['controller class'] = '';
  $entity_info['filter_format']['bundles'] = '';
}
