<?php

/**
 * @file
 * Integrates Drupal Entities with Doctrine ORM.
 */

function entity_init() {
//   module_load_install('entity');
//   entity_install();
  $user = doctrine()->find('Drupal\entity\User', 1);
  $debug = true;
}

/**
 * Implements hook_entity_info_alter().
 */
function entity_entity_info_alter(&$entity_info) {
  // Sets the entity class for users to a class test value.
  $entity_info['user']['entity class'] = 'Drupal\entity\User';

  $entity_info['filter_format']['label'] = 'Filter Format';
  $entity_info['filter_format']['fieldable'] = FALSE;
  $entity_info['filter_format']['base table'] = 'filter_format';
  $entity_info['filter_format']['entity class'] = 'Drupal\entity\FilterFormat';
  $entity_info['filter_format']['controller class'] = '';
  $entity_info['filter_format']['bundles'] = '';
}
